name: end-to-end tests chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: chrome
          headless: true
        env:
          NEXT_PUBLIC_API_URL: https://json-server-todo-tysl.herokuapp.com
